Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: Docker Compose CI
 
 on:
   push:
@@ -13,20 +13,21 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Set up Docker Compose
+      - name: Install Docker Compose
         run: |
-          docker-compose --version
+          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
+          docker-compose --version  # Проверка установки
 
-      - name: Start containers and wait for k6 to finish
+      - name: Start containers and wait for k6
         run: |
           docker-compose up -d
-          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_peak_load_stress)" = "true" ]; do
+          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_peak_load_stress 2>/dev/null)" = "true" ]; do
             sleep 1
           done
-          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_peak_load_stress)
-          echo "Container exited with code: $CONTAINER_EXIT_CODE"
+          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_peak_load_stress 2>/dev/null || echo 1)
           if [ "$CONTAINER_EXIT_CODE" -ne 0 ]; then
-            echo "Error: k6 test failed!"
+            echo "❌ k6 test failed!"
             exit 1
           fi
           docker-compose down
