Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,20 +18,15 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose --version  # Проверка установки
-
       - name: Start containers and wait for k6
         run: |
           docker-compose up -d
-          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_peak_load_stress 2>/dev/null)" = "true" ]; do
+          while [ "$(docker inspect -f '{{.State.Running}}' k6_lt_many_devices_low_rate 2>/dev/null)" = "true" ]; do
             sleep 1
           done
-          # Выводим логи и проверяем файлы
-          docker logs k6_lt_peak_load_stress || echo "⚠️ Failed to get logs"
-          docker exec k6_lt_peak_load_stress ls -l /k6 /tmp/k6-output || true
-          # Проверяем код выхода
-          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_peak_load_stress 2>/dev/null || echo 1)
+          CONTAINER_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' k6_lt_many_devices_low_rate 2>/dev/null || echo 1)
           if [ "$CONTAINER_EXIT_CODE" -ne 0 ]; then
-            echo "❌ k6 test failed! Exit code: $CONTAINER_EXIT_CODE"
+            echo "❌ k6 test failed!"
             exit 1
           fi
           docker-compose down
